
---  # config.yaml - Configuration file
# comment syntax 

# Basic syntax - key and value separated by colon and space before the value
key: value

# Scalar data types
stringValue: wer

transforms:
#rules to transform: á, é, í, ó, ú, ü, ñ, ¿, ¡
 - from: "á"
   to:   "a"
 - from: "é"
   to:   "e"
 - from: "á"
   to:   "a"
