
---  # config.yaml - Configuration file
# comment syntax 

# Basic syntax - key and value separated by colon and space before the value
key: value

# Scalar data types
integerValue: 1                     # integer value
octalNumber: 0123                     # Octal Numeric vale
hexaNumber: 0x4dea1                     # Hexa Decimal Numeric vale

floatingValue: 1                     # floating vale

stringValue: "456"                   # string with double quotes
stringValue: 'abc'                  # string with single quotes
stringValue: wer                   # string without quotes

booleanValue:true                   # boolean values - true or false

# Collection sequence data types
 # sequence ArrayList example
 - One
 - two
 - Three

  # Another way of sequence  syntax example
  [one, two, three]

### renaiming rules
  renamerules:
    rule001: ""~ "
    rule002: ""~ "
    rule003: ""~ "
    rule004: ""~ "
